name: classes_app
description: Classes App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"
  #flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  rename: ^1.2.0
  cupertino_icons: ^0.1.3
  http: ^0.12.0+3
  dio: 3.0.8
  shared_preferences: ^0.5.7+3
  flutter_swiper: ^1.1.6
  #date_utils: ^0.1.0+3
  intl: ^0.17.0
  flutter_html: ^0.11.1
  #webview_flutter: ^0.3.22+1
  
  #chewie: ^0.9.10
  video_player: ^0.10.12+5  
  youtube_player_flutter: ^7.0.0+7
  connectivity: ^0.4.9+5
  onesignal_flutter: ^2.4.1
  path_provider: ^1.6.9 
  flutter_downloader: ^1.5.1
  permission_handler: ^4.4.0+hotfix.4
  file_picker: ^1.13.3
  http_parser: ^3.1.4
  mime_type: ^0.2.7
  ext_storage: ^1.0.3
  flutter_local_notifications: ^0.9.1+3
  provider: ^4.1.2
  url_launcher: ^5.7.6
  rxdart: ^0.24.1
  pin_code_fields: ^3.1.2
  photo_view: ^0.9.2
  flutter_webview_plugin: ^0.3.11
  flutter_inappwebview: ^4.0.0+4
  auto_size_text: ^2.1.0
  flutter_tex: ^3.6.7+9
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: light
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf

  assets:
    - local_string/en.json
    - local_string/ar.json
    - local_string/fr.json
    - assets/images/ic_announcement.png
    - assets/images/ic_arrow_right.png
    - assets/images/ic_assigments.png
    - assets/images/ic_attendance.png
    - assets/images/ic_call_white.png
    - assets/images/ic_classroom.png
    - assets/images/ic_courses.png
    - assets/images/ic_doc.png
    - assets/images/ic_download.png
    - assets/images/ic_edit.png
    - assets/images/ic_exams.png
    - assets/images/ic_fees.png
    - assets/images/ic_filter.png
    - assets/images/ic_google_meet.png
    - assets/images/ic_image.png
    - assets/images/ic_mobile_number.png
    - assets/images/ic_notification.png
    - assets/images/ic_password.png
    - assets/images/ic_pay_online.png
    - assets/images/ic_pdf.png
    - assets/images/ic_radio_check.png
    - assets/images/ic_radio_uncheck.png
    - assets/images/ic_skype.png
    - assets/images/ic_study_material.png
    - assets/images/ic_submit.png
    - assets/images/ic_txt.png
    - assets/images/ic_user_name.png
    - assets/images/ic_video.png
    - assets/images/ic_view.png
    - assets/images/ic_youtube.png
    - assets/images/ic_zoom.png
    - assets/images/iconsapp.png
    - assets/images/report.png